minimumDistanceDifference: 0.25 #0.25 will only trigger when sprinting.
speed: 3 #potion effectiveness
duration: 60 #duration in ticks (20 ticks = appr. 1 second)
timePassedBeforeCheck: 20 #the time that has to be passed for players with a speed buff before checking if they're walking on ice. In ticks (20 ticks = appr. 1 second)
defaultname: '{PLAYER} zijn schaatsen'
playerspecificskateitems: true
enableskateitems: true
defaultlore:
- Schaatsen
- Gebruik deze schaatsen om snel over ijs te schaatsen!
enchantments:
- PROTECTION_ENVIRONMENTAL,4
- PROTECTION_FALL,4
- DEPTH_STRIDER,3
- FROST_WALKER,2
- DURABILITY,3
- MENDING,1